### ISSUE TITLE
Include a polars backend?

### ISSUE THREAD

**Issue by denehoffman** [scikit-hep/uproot5#1264]
Now that [polars](https://docs.pola.rs/) is out of v0, it would be nice to have some features to stream directly to polars dataframes. Currently it's not difficult to convert the `library='np'` output to a polars dataframe (`pl.DataFrame(ttree.arrays(library='np'))` usually does the trick), but it might be interesting to directly read to one, especially in cases where streaming and lazy evaluation become important (large files). Again, this is not a feature I need right now (or have the knowledge to write myself), just might be something to look at in the future.

**Comment by denehoffman** [comment]
I just realized this is very related to https://github.com/scikit-hep/uproot5/issues/1261, but it could also just be done through the py-polars frontend without any Rust involvement from the uproot side.

**Comment by jpivarski** [comment]
In fact, it's even more related to #1096. I should label this issue as a duplicate and you should follow up on #1096.
