### ISSUE TITLE
Wildcards on XRootD paths don't work

### ISSUE THREAD

**Issue by OnkelAsriel** [scikit-hep/uproot5#193]
The following is not working on uproot4 (I thought the equivalent worked in uproot 3, but no, sorry!):

```python
for file in uproot.iterate("root://somepath/*root:Data", ["zData", "channel"], step_size="1 GB"):
   print(file)
```

If I specify the name of a single file, then it does work.

I am using uproot4 0.1.2 with xrootd 4.12.3

**Comment by jpivarski** [comment]
This is a reasonable feature request, but I don't see how that could have worked in Uproot 3. There was never any code for asking XRootD to match wildcards. Both versions pass the string with all characters unmodified to the server (except that "`:Data`" gets stripped off). Even if the server could resolve the wildcards to a set of files, both versions of Uproot have assumed that what you get back from the server is one file, not multiple. (I'm not sure how that would be represented.)

Are you sure that this worked in Uproot 3? I'm happy to make it a feature request for Uproot 4, but I'm confused about how it might have accidentally worked in Uproot 3, if at all.

**Comment by asnaylor** [comment]
I tried wildcarding with xRootD paths using `uproot.iterate` for both uproot3 and uproot4 and got `OSError: [ERROR] Server responded with an error: [3011] No such file`. I'm pretty sure i've used wildcarding with xRootD paths before with uproot3 so maybe something recently has broken.

As a temporary work around I found I could still get the files paths with wildcarding using `XRootD.client.glob_funcs.glob` and then pass the resulting array of xrootd files paths into `uproot.iterate` and it worked.

**Comment by jpivarski** [comment]
Your workaround can be the basis of adding this feature in the future.

But as for Uproot 3, if it ever worked before, it was an accident—"broken" doesn't describe the lack of that feature now.

**Comment by OnkelAsriel** [comment]
Thanks! Sorry if I misremembered :-) I'll edit the OP.
It would be a very useful feature.

**Comment by jpivarski** [comment]
With XRootD being handled by [fsspec-xrootd](https://github.com/CoffeaTeam/fsspec-xrootd) now, I believe this is working. (I remember seeing some tests in the test suite that used wildcards on an XRootD server.)
