### ISSUE TITLE
Reading files from S3 with authenticated http headers (s3http, s3https)

### ISSUE THREAD

**Issue by wdconinc** [scikit-hep/uproot5#443]
The Electron Ion Collider (EIC) is storing large data set on storage servers that we access via the S3 protocol. Reading from these files is currently not supported by uproot since dedicated [signed authentication headers](https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html) are required.

ROOT has support for the S3 (and Google Storage) protocol in [TS3WebFile](https://root.cern.ch/doc/master/TS3WebFile_8cxx_source.html) and [TS3HTTPRequest](https://root.cern.ch/doc/master/TS3HTTPRequest_8cxx_source.html). This allows for specifying files with s3http:// and s3https:// protocols (as well as gshttp:// and gshttps://).

I am filing this issue as way to keep track of discussion, suggestions, and other interested parties. I will be opening a WIP PR when we have some code that others may want to comment on. Currently we are anticipating that we will be able to implement this as a modification of `src/uproot/source/http.py` rather than by adding an entirely new physical layer.

**Comment by wdconinc** [comment]
The user-facing interface strategy would be to support `s3http://` and `s3https://` URLs with specification of the S3 credentials in one of the following methods:
- environment variables `S3_ACCESS_KEY` and `S3_SECRET_KEY` (as done by TS3WebFile),
- syntax `s3http://S3_ACCESS_KEY:S3_SECRET_KEY@example.com` to emulate the `AUTH=S3_ACCESS_KEY:S3_SECRET_KEY` optional argument in TS3WebFile (this mirrors the approach for basic authentication for https connections).

**Comment by jpivarski** [comment]
#692 would likely be the best way forward. Hopefully, we can find someone to take this up again (as I understand it, @nsmith- is very busy!). I can help with ensuring that it fits the `Source` protocol (connection to Uproot).
