### ISSUE TITLE
Include an option to use the "deflate" library instead of Python's built-in "zlib"

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/uproot5#518]
This one: https://pypi.org/project/deflate/

@Moelf and @aminnj have shown that using this third-party library gives a 30% performance improvement. Uproot and UnROOT used to have about the same speed, but replacing standard "zlib" with "deflate" in UnROOT sped it up by 30%. Compare Uproot:

![image](https://user-images.githubusercontent.com/1852447/144336866-cb7caa42-bf08-4606-8dfc-733c1446f0aa.png)

with UnROOT:

![image3](https://user-images.githubusercontent.com/1852447/144338067-92365ec8-b80d-4505-ba4f-a930524b1ec6.png)

(Cross-reference to an UnROOT issue?)

**Comment by Moelf** [comment]
wait, the first screenshot is on two different branches, the point was to that it's not limited to flat branch (one might think that's the only place where decompression dominates)

**Comment by jpivarski** [comment]
> the first screenshot is on two different branches of the TTree, the point was to that it's not limited to flat branch (one might think that's the only place where decompression dominates)

I updated the original message with a better presentation of the demo.

**Comment by aminnj** [comment]
UnROOT issue: https://github.com/tamasgal/UnROOT.jl/pull/137
With some more discussion linked within

The benchmark file comes from http://opendata.cern.ch/record/12341

**Comment by jpivarski** [comment]
This could piggyback on #1090's interface to use alternate ZLIB libraries. That PR introduces a back-door to add ISAL.

How does deflate compare with ISAL (in decompression time and compressed file size)? Do we want two back doors?
