### ISSUE TITLE
Add citation metadata wtih CITATION.cff

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/uproot5#604]
If there is interest, it would be nice to add a [`CITATION.cff`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) especially as there is already a [Zenodo archive for `uproot`](https://doi.org/10.5281/zenodo.4340632). I would be happy to make the PR.

**Comment by jpivarski** [comment]
It has been a goal of mine to get a CITATION.cff for Uproot. The only thing that has been keeping me from it is the process of defining the author list. Just as in [awkward/CITATION.cff](https://github.com/scikit-hep/awkward/blob/main/CITATION.cff), I wanted to highlight the main authors and get full information for them. The list of GitHub userids that Zenodo pulls in doesn't include institutions, email addresses, or ORCIDs.

Do you have an idea in mind for curating the list of authors? I'm thinking I should acknowledge the fact that I got a _lot_ of help on the remote backends part.

Also desirable for CITATION.cff (across projects, in my opinion): it should reference the versionless DOI for the repo. For instance, in Awkward Array, it's

https://github.com/scikit-hep/awkward/blob/8a4ea2b8c1c0cb2c92dab3565511bf5a717b7703/CITATION.cff#L4

which always goes to the latest version, whatever that is. It's therefore a stable identifier across time. For Uproot, this would be `10.5281/zenodo.4340632`.

**Comment by matthewfeickert** [comment]
> It has been a goal of mine to get a CITATION.cff for Uproot. The only thing that has been keeping me from it is the process of defining the author list. Just as in [awkward/CITATION.cff](https://github.com/scikit-hep/awkward/blob/main/CITATION.cff), I wanted to highlight the main authors and get full information for them. The list of GitHub userids that Zenodo pulls in doesn't include institutions, email addresses, or ORCIDs.
> 
> Do you have an idea in mind for curating the list of authors? I'm thinking I should acknowledge the fact that I got a _lot_ of help on the remote backends part.

Not really anything rigorous. I think on a smaller project like `pyhf` it is easier to define who the "development" team is and treat them as [the `authors`](https://github.com/scikit-hep/pyhf/blob/aed69b54e13340129251cabe7840f31a525f0cde/CITATION.cff#L4). So I think that you'd either need to create an authorship criteria that seems fair to you, or just make selections on who has historically provided the help on the backends and then put that together. I assume that you mean contributions from across https://github.com/scikit-hep/uproot3 and https://github.com/scikit-hep/uproot4?

> Also desirable for CITATION.cff (across projects, in my opinion): it should reference the versionless DOI for the repo. For instance, in Awkward Array, it's
> 
> https://github.com/scikit-hep/awkward/blob/8a4ea2b8c1c0cb2c92dab3565511bf5a717b7703/CITATION.cff#L4
> 
> which always goes to the latest version, whatever that is. It's therefore a stable identifier across time. For Uproot, this would be `10.5281/zenodo.4340632`.

Yup. That's what I linked to above in

> especially as there is already a [Zenodo archive for `uproot`](https://doi.org/10.5281/zenodo.4340632)

and we do [the same for `pyhf`](https://github.com/scikit-hep/pyhf/blob/aed69b54e13340129251cabe7840f31a525f0cde/CITATION.cff#L19).

**Comment by jpata** [comment]
Perhaps related to this issue: is there a recommended list of proceedings/papers to cite for uproot (also for awkward)?
Should it be somewhere in the README?

**Comment by jpivarski** [comment]
Uproot doesn't have one yet (I have to draw up an author list), but Awkward Array does:

https://github.com/scikit-hep/awkward/blob/main/CITATION.cff

![image](https://user-images.githubusercontent.com/1852447/175057897-4be0110d-cfc6-4072-8cda-224fba5c825e.png)

**Comment by matthewfeickert** [comment]
> Perhaps related to this issue: is there a recommended list of proceedings/papers to cite for uproot (also for awkward)? Should it be somewhere in the README?

@jpivarski I think @jpata is referring to something along the lines of how [`pyhf`'s `CITATION.cff` includes other papers to cite in the `references` section](https://github.com/scikit-hep/pyhf/blob/86229ad3257ddbbdb78548d7ceade5c9ab683a0c/CITATION.cff#L43-L71) and then we also ask for people to cite both the software and the JOSS paper in [the README](https://github.com/scikit-hep/pyhf/blob/86229ad3257ddbbdb78548d7ceade5c9ab683a0c/README.rst?plain=1#L310-L330) and [the docs](https://github.com/scikit-hep/pyhf/blob/86229ad3257ddbbdb78548d7ceade5c9ab683a0c/docs/citations.rst?plain=1#L11-L15).

**Comment by jpivarski** [comment]
In that case, no, I don't think there's a good paper that would be an overview of Uproot or Awkward Array in general. Each is covering something specific, or was written at a time when the idea wasn't fully formed. I would just cite the software, not any accompanying paper.

**Comment by jpivarski** [comment]
This is done.
