### ISSUE TITLE
Drawing of histograms created in uproot fails in ROOT

### ISSUE THREAD

**Issue by dcervenkov** [scikit-hep/uproot5#696]
When saving a histogram in a ROOT file using Uproot, if the content of the last bin in the histogram is negative, ROOT will fail to plot it. The error message is 
```
TCanvas::ResizePad:0: RuntimeWarning: Inf/NaN propagated to the pad. Check drawn objects.
TCanvas::ResizePad:0: RuntimeWarning: Canvas_1 height changed from 0 to 10
```
If the last bin's content is non-negative, plotting works.

To reproduce, create the histogram
```py
import numpy as np
import uproot

with uproot.recreate("test.root") as f:
    f["hist_fail"] = (np.asarray([-3, -2, -1]), np.asarray([0, 1, 2, 3]))
    f["hist_pass"] = (np.asarray([-3, -2, +1]), np.asarray([0, 1, 2, 3]))
```
Opening `test.root` using `rootbrowser` (or just `root`, getting the histograms, and plotting them using `Draw()`) results in the `hist_pass` being drawn, while `hist_fail` won't be.

Furthermore, even the `hist_pass` isn't drawn properly - the y-axis starts at 0. When creating the same histogram in ROOT, the range includes all the events.

I think the issue is caused by the errors of the histogram bins - ROOT initializes them as `sqrt(abs(content))` while uproot uses `sqrt(content)`, leading to `nan`s for negative numbers. Not sure what is special about the last bin, though.

Uproot 4.3.4
ROOT 6.26/04

**Comment by Moelf** [comment]
@jpivarski can we even write in the sumw2 information from `uproot`? because that's needed

**Comment by jpivarski** [comment]
The 2-tuple of arrays is recognized as a histogram with this:

https://github.com/scikit-hep/uproot5/blob/49d40bd623b4b2ca19369ae07f9756e65dc6d122/src/uproot/writing/identify.py#L420-L427

and this is the TH1 that it creates:

https://github.com/scikit-hep/uproot5/blob/49d40bd623b4b2ca19369ae07f9756e65dc6d122/src/uproot/writing/identify.py#L453-L471

The `data` and the `fSumw2` are deliberately set to the same input. We can see the conversion without having to actually write to a file using [uproot.to_writable](https://uproot.readthedocs.io/en/latest/uproot.writing.identify.to_writable.html):

```python
>>> uproot.to_writable((np.asarray([-3, -2, -1]), np.asarray([0, 1, 2, 3])))
<TH1D (version 3) at 0x7eff8030c730>
```

and that writable has a JSON form, so we can look directly at the `fSumw2` that it makes:

```python
>>> uproot.to_writable((np.asarray([-3, -2, -1]), np.asarray([0, 1, 2, 3]))).tojson()["fSumw2"]
[0.0, -3.0, -2.0, -1.0, 0.0]
```

and we can even go full round trip to PyROOT:

```python
>>> uproot.pyroot.to_pyroot(uproot.to_writable((np.asarray([-3, -2, +1]), np.asarray([0, 1, 2, 3]))))
<cppyy.gbl.TH1D object at 0x55f83cd0e580>
```

and look at its JSON serialization:

```python
>>> json.loads(
...     str(
...         ROOT.TBufferJSON.ToJSON(
...             uproot.pyroot.to_pyroot(
...                 uproot.to_writable((np.asarray([-1, -2, -3]), np.asarray([0, 1, 2, 3])))
...             )
...         )
...     )
... )["fSumw2"]
[0, -1, -2, -3, 0]
```

But okay, maybe `fSumw2` shouldn't be identical to `data`? Maybe it should be the absolute value?

**Comment by jpivarski** [comment]
`fSumw2` represents the _square_ of the value? I had been misinterpreting that.

```python
>>> h = ROOT.TH1F("h", "", 3, 0.0, 3.0)
>>> h.Fill(0.5, -3.0)
1
>>> h.Fill(1.5, -2.0)
2
>>> h.Fill(2.5, -1.0)
3
>>> json.loads(str(ROOT.TBufferJSON.ToJSON(h)))["fSumw2"]
[0, 9, 4, 1, 0]
```

**Comment by jpivarski** [comment]
No, that's not quite it:

```python
>>> h = ROOT.TH1F("h", "", 3, 0.0, 3.0)
>>> h.Fill(0.5, -1.0); h.Fill(0.5, -1.0); h.Fill(0.5, -1.0)
1
1
1
>>> h.Fill(1.5, -1.0); h.Fill(1.5, -1.0)
2
2
>>> h.Fill(2.5, -1.0)
3
>>> json.loads(str(ROOT.TBufferJSON.ToJSON(h)))["fSumw2"]
[0, 3, 2, 1, 0]
```

This is looking like information that you can't determine from the values `np.histogram` gives you. These two ways of filling `h` result in the same values but different `fSumw2`.

**Comment by jpivarski** [comment]
My assumption had been that [np.histogram](https://numpy.org/doc/stable/reference/generated/numpy.histogram.html) was called without a `weights` argument. After the histogram has been filled and we're left with only the 2-tuple of arrays, we can't know what the `weights` had been, if anything.

**Comment by Moelf** [comment]
It's the sum of weight^2 of all the events ever filled into that bin, it's critical in doing bin errors correctly

**Comment by Moelf** [comment]
We can default to assuming all weights was 1 so just set keep doing what we do now, but we should add a 3-tuple logic so user can supply sumw2 array manually

**Comment by jpivarski** [comment]
We didn't invent the 2-tuple convention, and I think a 3-tuple would be interpreted as a 2D histogram. (These are things NumPy made up a long time ago and it's a pervasive enough convention that a lot of other libraries recognize it, such as Matplotlib.)

I think the "right" way to deal with this is to not set the `fSumw2` from a NumPy histogram (i.e. not lie) and if you want weights, you have to use a real histogramming package like boost-histogram or hist. They have different `Storage` types for with-errors, without-errors, etc.

**Comment by jpivarski** [comment]
Until now, any histogram-writing without error information has assumed that the histograms were filled with all weights equal to 1. This might have been the right assumption for some people and the wrong assumption for others, but it really broke down when the weight was not only not 1, but negative.

(What it has to do with the last bin is a question for the internals of ROOT: we gave it values, it showed us that it got them, and then it drew something strange. But clearly, we were breaking one of ROOT's assumptions, so it's undefined behavior.)

Histograms from NumPy have no weight information and should set `fSumw2` to `[]`. Histograms from boost-histogram or hist have weight information if you set the appropriate [Storage](https://hist.readthedocs.io/en/latest/user-guide/storages.html) option. If `Storage` is not `Weight`, these histograms should also have a `fSumw2` of `[]`. I have evidence that ROOT expects `fSumw2` to be `[]` and interprets that as "no weights":

```python
>>> h = ROOT.TH1F("h", "", 3, 0.0, 3.0)
>>> json.loads(str(ROOT.TBufferJSON.ToJSON(h)))["fSumw2"]
[]
```

It draws differently (skyline instead of error bars).

PR #698 fixes this for Uproot v5 and PR #699 fixes this for Uproot v4. If you (@dcervenkov) can try what you were doing that led to this discovery and everything looks okay, then I'll merge the PRs and make a new bug-fix release for the v4 series right away. Thanks for finding it!

**Comment by Moelf** [comment]
LGTB as far as bug fixing goes.

But I still have the related question of how to write a histogram with error (or equivalently sumw2)

**Comment by jpivarski** [comment]
NumPy's tuple representation leaves a lot to be desired—I checked and a 3-tuple would indeed be interpreted as a 2D histogram. This is why I've said that one of the things the scientific Python ecosystem lacks is HEP-style histograms. If we're doing anything non-trivial, and plotting error bars on a histogram is well beyond what someone outside of HEP would call trivial, we have to go to a package that actually specializes in histogram objects.

Here are some tests that use hist to make histograms,

https://github.com/scikit-hep/uproot5/blob/49d40bd623b4b2ca19369ae07f9756e65dc6d122/tests/test_0580-round-trip-for-no-flow-histograms.py#L14-L46

but I don't think they include errors. The [hist documentation](https://hist.readthedocs.io/) covers all of this, and in particular, the page on [Storages](https://hist.readthedocs.io/en/latest/user-guide/storages.html) shows how to include weights.

There are some weighted histograms in the Uproot tests, but they're round trips from ROOT to Uproot to ROOT again.

**Comment by dcervenkov** [comment]
@jpivarski I can confirm that both #698 and #699 fix the issue. Feel free to close this issue.

**Comment by Moelf** [comment]
@dcervenkov you might be interested in this workaround:
```python
def make_TH1D(title, entries, edges, sumw2=None):
    with_flow = numpy.empty(len(entries) + 2, dtype=">f8")
    with_flow[1:-1] = entries
    with_flow[0] = 0
    with_flow[-1] = 0
    fEntries=entries.sum()
    fTsumw, fTsumw2, fTsumwx, fTsumwx2 = uproot.writing.identify._root_stats_1d(entries, edges)
    fNbins = len(edges) - 1
    fXmin, fXmax = edges[0], edges[-1]
    return uproot.writing.identify.to_TH1x(
            None,
            title,
            data=with_flow,
            fEntries=fEntries,
            fTsumw=fTsumw,
            fTsumw2=fTsumw2,
            fTsumwx=fTsumwx,
            fTsumwx2=fTsumwx2,
            fSumw2=sumw2,
            fXaxis=uproot.writing.identify.to_TAxis(
                fName="xaxis",
                fTitle="",
                fNbins=fNbins,
                fXmin=fXmin,
                fXmax=fXmax,
                fXbins=edges,
                )
            )
```

then you can encode sumw2 yourself:
```python

In [84]: t1 = make_TH1D("hist", np.array([1,2,3]), np.array([1,10,20,30]), np.array([0.5, 0.8, 2.3]))

In [86]: import ROOT

In [87]: with up.recreate("/tmp/test.root") as file:
    ...:     #akform =  ak._v2.forms.RecordForm([ak._v2.forms.NumpyForm('int32')], ['one_integers'])
    ...:     file["hist"] = t1

In [91]: f = ROOT.TFile("/tmp/test.root")

In [92]: list(ROOT.TH1D(f.Get("hist")).GetSumw2())
Out[92]: [0.5, 0.8, 2.3]

```

**Comment by dcervenkov** [comment]
Hi @Moelf, thanks for the shout-out. #699 and release 4.3.5 fixed my issue. However, what you suggest is a way to write TH1D with Sumw2 - doesn't this already work when you use histograms that support this, i.e., `hist` or `boost_histogram`? Or am I missing something?

**Comment by Moelf** [comment]
I don't think they include errors

**Comment by jpivarski** [comment]
hist and boost-histogram have errors (and therefore `fSumw2`, when converted to ROOT) if you set the [Storage type](https://hist.readthedocs.io/en/latest/user-guide/storages.html) to `Weight` instead of, say, `Double`.
