### ISSUE TITLE
Threads staying open after `uproot.num_entries`

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/uproot5#712]
When using `uproot.num_entries` to read the number of entries for a lot of remote files, I eventually run into `RuntimeError: can't start new thread`. I cannot reproduce this with local files. This is tested with `uproot` version 4.3.5.
```python
import uproot
import threading

for _ in range(10):
    next(uproot.num_entries("https://github.com/scikit-hep/scikit-hep-testdata/"\
            "blob/main/src/skhep_testdata/data/uproot-HZZ.root?raw=true:events"))
    print(threading.active_count())
```
output:
```
2
3
4
5
6
7
8
9
10
11
```

**Comment by agoose77** [comment]
It looks like we never close the executors, so their resources (threads) accumulate until exhaustion of the limit.
