### ISSUE TITLE
Contributors who are missing from all-contributors

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/uproot5#727]
Hi, I was scanning through contributions to Uproot and realized that I missed some. I'll close this issue when all are included.

**Comment by jpivarski** [comment]
@all-contributors please add @veprbl for code and infra

**Comment by jpivarski** [comment]
@all-contributors please add @nikoladze for code

**Comment by jpivarski** [comment]
@all-contributors please add @klieret for docs

**Comment by jpivarski** [comment]
@all-contributors please add @dcervenkov for code

**Comment by jpivarski** [comment]
@all-contributors please add @beojan for code

**Comment by jpivarski** [comment]
This is everybody that I know of. Sorry for the extra emails!

**Comment by agoose77** [comment]
@jpivarski if you've added me to the CITATION.cff intentionally, and that is expected to be synchronised with all-contributors, then I should probably be added too. Otherwise, if you want to wait until I've gotten around to bigger contributions, no problem!

**Comment by jpivarski** [comment]
🤦‍♂️

https://github.com/all-contributors please add @agoose77 for code and maintenance

**Comment by jpivarski** [comment]
Does the bot only respond to open issues/PRs?

@all-contributors please add @agoose77 for code and maintenance

No, I just pasted a URL instead of the at-sign-name. This should do it.
