### ISSUE TITLE
Support for TLeafG

### ISSUE THREAD

**Issue by oksuzian** [scikit-hep/uproot5#761]
I have a tree with TLeafG type.
When I try to process it, I get the following:

```
name                 | typename                 | interpretation                
---------------------+--------------------------+-------------------------------
runNumber            | int32_t                  | AsDtype('>i4')
subrunNumber         | int32_t                  | AsDtype('>i4')
timestamp            | unknown                  | <UnknownInterpretation 'non...
```

Would it be possible to add the support for TLeafG type in identify.py?

Thanks, Yuri.

What you're looking for might already be possible as a combination of existing functions, so these requests might get converted into requests for documentation (with a corresponding change in title).

Here are some links to documentation, to help you in your search.

   * [The tutorials site](https://uproot.readthedocs.io/)
   * [StackOverflow: [uproot] tag](https://stackoverflow.com/questions/tagged/uproot)
   * [Gitter: Scikit-HEP/uproot room](https://gitter.im/Scikit-HEP/uproot)

**Comment by jpivarski** [comment]
That's surprising; I didn't know about [TLeafG](https://root.cern.ch/doc/master/classTLeafG.html). According to the ROOT documentation (that link), it's for 64-bit integers, but [TLeafL](https://root.cern.ch/doc/master/classTLeafL.html) is also for 64-bit integers.

It is probably just a matter of copy-pasting some `TLeafL` stuff to also be named `TLeafG` (or linking/renaming?).

But that's weird: `TLeafG`! Maybe one of these is guaranteed to be 64-bit on all systems and the other isn't? (32-bit Windows?) But it's an I/O class, so it can't be platform-dependent without making the files unreadable on different platforms. Very weird.

Hmmm... It's [from 2020](https://github.com/root-project/root/commits/master/tree/tree/src/TLeafG.cxx).
