### ISSUE TITLE
Very slow reading of some (not all) vector<vector<int>> variables

### ISSUE THREAD

**Issue by mpad** [scikit-hep/uproot5#850]
Dear uproot,

One of my ROOT file contains `vector<vector<int>>` variables which are all produced in a very similar way.
Out of 4, 2 of them are extremely slow to read with uproot (5.0.3) : 
```python
t= uproot.open("test.root:gnnjet")
>>> timeit.timeit("a=t.arrays(['nnTruthReco' ])", globals=globals(), number=1)
6.898946930188686
>>> timeit.timeit("a=t.arrays(['nnRecoReco' ])", globals=globals(), number=1)
0.03529514092952013
>>> timeit.timeit("a=t.arrays(['nnRecoTruth' ])", globals=globals(), number=1)
5.870497648837045
>>> timeit.timeit("a=t.arrays(['nnTruthTruth' ])", globals=globals(), number=1)
0.06448978511616588
```

As you can see there seem to be a factor>100 in the read time for 2 of the variables. 
This is a  test file with 1000 entries which can be found at : 
https://cernbox.cern.ch/s/rvpBMjWLCZfhatG

My complete files have ~100k entries  so they are practically unreadable...
Is there something wrong with these files ?  Or is the slowness coming from uproot ?

Thanks for any hint !

P-A

```python
# python version is 3.10.9
>>> import uproot
>>> uproot.__version__
'5.0.3'
```

**Comment by Moelf** [comment]
can you try 5.0.4?
```python
In [1]: import uproot

In [2]: t= uproot.open("test.root:gnnjet")

In [5]: %timeit t.arrays(['nnTruthReco' ])
508 µs ± 55.9 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [6]: %timeit t.arrays(['nnRecoReco' ])
13.3 ms ± 39.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]: uproot.__version__
Out[7]: '5.0.4'
```

**Comment by mpad** [comment]
Hi,

Thanks for the fast feedback !
I don't have ipython but could update to 5.0.4 : 
```python

>>> import uproot
>>> uproot.__version__
'5.0.4'
>>> t=uproot.open("test.root:gnnjet")
>>> timeit.timeit("a=t.arrays(['nnTruthReco' ])", globals=globals(), number=1)
6.966970829991624
>>> timeit.timeit("a=t.arrays(['nnRecoReco' ])", globals=globals(), number=1)
0.05337693099863827
```  
I see the same behaviour. 

But I'm not sure I understand your tests : there are many runs (aren't you re-using the cache? ) and a different number of loops...

**Comment by Moelf** [comment]
you're right, I think cache is involved:
```python
In [8]: %timeit uproot.open("test.root:gnnjet").arrays(['nnRecoReco'])
39.5 ms ± 102 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [9]: %timeit uproot.open("test.root:gnnjet").arrays(['nnTruthReco'])
5.11 s ± 66.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

the different number of loops is just heuristics of `%timeit`, the final number is always correctly averaged

**Comment by jpivarski** [comment]
The fact that the data types are `std::vector<std::vector<int>>` and the performance differences you're seeing are factors of ~100 makes me suspicious that the fast ones are using the new AwkwardForth optimization and the slow ones are not. I'm looking into it.

**Comment by jpivarski** [comment]
I'm glad the differences in performance were large enough for you to have noticed!

Although the consequences of this are only in performance, not correctness of the output, it resulted in taking a completely different code-path for very similar TBranches, which is not something we want. (It could _lead_ to a subtle bug.)

**Comment by mpad** [comment]
Hey, glad it could help a little and thanks for the super fast reaction !
