### ISSUE TITLE
'AwkwardExtensionArray' object is not callable

### ISSUE THREAD

**Issue by sbdrchauhan** [scikit-hep/uproot5#895]
![image](https://github.com/scikit-hep/uproot5/assets/58833553/0c771a5d-7503-45be-a591-45e160055071)

![image](https://github.com/scikit-hep/uproot5/assets/58833553/c0cf7467-67ea-403c-bc71-18939682ec3b)

I hope my problem is self explanatory by images. Thank you.

**Comment by sbdrchauhan** [comment]
I want this feature ON for pandas df so my life becomes lot easier. Thanks.

![image](https://github.com/scikit-hep/uproot5/assets/58833553/7de364e8-a776-46d4-8378-c72b63f1ec8e)

**Comment by jpivarski** [comment]
@douglasdavis, should I move this issue to https://github.com/intake/awkward-pandas?

**Comment by douglasdavis** [comment]
Yes I think that would make sense

**Comment by jpivarski** [comment]
I'll need a higher level of access ("Write" access).

**Comment by douglasdavis** [comment]
Ah, should be taken care of now

**Comment by jpivarski** [comment]
I don't know why, but GitHub isn't letting me transfer this. I manually transferred it as https://github.com/intake/awkward-pandas/issues/31.

**Comment by jpivarski** [comment]
Ah, my mistake was that I had to accept an invitation, first!
