### ISSUE TITLE
Request for support of writing hist-derived profiles

### ISSUE THREAD

**Issue by raymondEhlers** [scikit-hep/uproot5#908]
I'd like to request writing support for profile hists that are coming from hist/boost-histogram. The use case I ran into was merging some root files containing a variety of histograms. My procedure was roughly:

1. Read file
2. Retrieve hists, and convert using to_hist to take advantage of the `__add__` functionality already implemented
3. Add the hists
4. Write the merged hists to file

The issue is in step 4. This works fine for standard histograms, and from the docs I understand that it should work for TProfile objects that aren't converted to hist (eg. just read by uproot, and still contained in a Model), but it doesn't work after I've done the conversion. Looking into the exception that's raised

https://github.com/scikit-hep/uproot5/blame/a9f4374607b7434ef89ebec82c784d34bfc31413/src/uproot/writing/identify.py#L248-L255

the `NotImplementedError` obviously suggests that profiles intentionally aren't supported at the moment, but the `ValueError` suggests that perhaps they were intended to be? In any case, adding support for writing profiles would be much appreciated, and would make merging hists a bit easier (this would be helpful because `hadd` isn't always available). Thanks!

**Comment by jpivarski** [comment]
I've had this in my email inbox for a week in order to say something intelligent about it, but all I can say is, yes: that would be a very good feature to have. Hopefully, we'll be able to get more effort on Uproot because there are a few important requests like this one.

I'll just note that this is a high-priority item.

**Comment by raymondEhlers** [comment]
Thanks for your response! I know that I'm making a request for a new feature without offering to actually help on the implementation, so I have no expectations about the timeline. (From what I can tell, it needs some expertise on PlottableHistogram that I don't have, but if you think it's something that could be completed in a couple of hours for someone new to the uproot internals, I'm willing to give it a shot).

As always, thanks for all of your efforts!

**Comment by jpivarski** [comment]
PR #1000 ensures that TProfiles can be read from ROOT and written to ROOT with 100% fidelity. It doesn't show that they can be taken from or to hist/boost-histogram, but that's a separate issue. When this is closed by PR #1000 getting merged, you may still want to check that.

The thing I'm uncertain about is whether hist/boost-histogram's `WeightedMean` histograms have enough per-bin data to represent a ROOT (HBOOK, SUMX, ...)-style "profile plot," which is [more involved](https://root.cern.ch/doc/master/classTProfile.html) than simply tracking the weighted mean of each bin.

**Comment by raymondEhlers** [comment]
Thanks for implementing this! I ran some tests as a brief follow up and writing `hist` objects works as requested, thanks!

For my overall goal of merging and saving profiles, I think something is still going wrong around the to/from hist conversion (as you suspected). eg. If I add two `WeightedMean()` profiles created via hist, I get the correct answer, but if I read a profile via uproot, convert to_hist and then add them, I get the wrong answer. In any case, the new writing support is good progress, and I'll have to dig into this further in another issue some other time
