### ISSUE TITLE
AttributeError: module 'uproot._util' has no attribute 'awkward_form_remove_uproot'

### ISSUE THREAD

**Issue by aliyilmaz1** [scikit-hep/uproot5#919]
Hi I have tried to open root file from DelphesSchema as

>>> import uproot
>>> uproot.__version__
'5.0.10'
>>> 

import awkward as ak
import cabinetry
from coffea.nanoevents import *
from coffea.nanoevents.schemas.delphes import DelphesSchema, zip_forms

import uproot # for reading .root files
import numpy as np # for numerical calculations such as histogramming
import utils  # contains code for bookkeeping and cosmetics, as well as some boilerplate

fname = "/Volumes/wd3TB/mg5Works/pp2zz_HLLHC_HELHC_LEFCC/production/dataFiles/cx_CBtWL4/E37.5/run-1/Events/cv3.5/zz_delphes_events.root"

events = NanoEventsFactory.from_root(
    fname, schemaclass=DelphesSchema, treepath="Delphes"
)

data = events.events()
mask = ak.num(data.Electron) >= 1

electrons = data.Electron[mask]
leading_electrons = electrons[:,0]
print(electrons.pt)
print(leading_electrons.pt)

and it is failing with

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[11], line 3
      1 fname = "/Volumes/wd3TB/mg5Works/pp2zz_HLLHC_HELHC_LEFCC/production/dataFiles/cx_CBtWL4/E37.5/run-1/Events/cv3.5/zz_delphes_events.root"
----> 3 events = NanoEventsFactory.from_root(
      4     fname, schemaclass=DelphesSchema, treepath="Delphes"
      5 )

File /usr/local/anaconda3/lib/python3.10/site-packages/coffea/nanoevents/factory.py:124, in NanoEventsFactory.from_root(cls, file, treepath, entry_start, entry_stop, runtime_cache, persistent_cache, schemaclass, metadata, uproot_options, access_log, iteritems_options)
    117 mapping = UprootSourceMapping(
    118     TrivialUprootOpener(uuidpfn, uproot_options),
    119     cache={},
    120     access_log=access_log,
    121 )
    122 mapping.preload_column_source(partition_key[0], partition_key[1], tree)
--> 124 base_form = mapping._extract_base_form(
    125     tree, iteritems_options=iteritems_options
    126 )
    128 return cls._from_mapping(
    129     mapping,
    130     partition_key,
   (...)
    135     metadata,
    136 )

File /usr/local/anaconda3/lib/python3.10/site-packages/coffea/nanoevents/mapping/uproot.py:105, in UprootSourceMapping._extract_base_form(cls, tree, iteritems_options)
    101 if cls._fix_awkward_form_of_iter:
    102     form = uproot._util.recursively_fix_awkward_form_of_iter(
    103         awkward, branch.interpretation, form
    104     )
--> 105 form = uproot._util.awkward_form_remove_uproot(awkward, form)
    106 form = json.loads(
    107     form.tojson()
    108 )  # normalizes form (expand NumpyArray classes)
    109 try:

AttributeError: module 'uproot._util' has no attribute 'awkward_form_remove_uproot'

How can I solve this issue, can you guide me about it, please?

thank you

**Comment by jpivarski** [comment]
This is a major version mismatch (that is, the `X` in `X.Y.Z`). Uproot v5 does not have this function (removed in #770), and these libraries need to be matched up by major version number:

| | old | new |
|:-|:-:|:-:|
| Uproot | 4.* | 5.* |
| Awkward Array | 1.* | 2.* |
| Coffea | 0.7.* | 2023.* |

A package manager is supposed to maintain these version constraints, but maybe you installed differently? Or you have multiple installations and they're not fully isolated?

**Comment by NJManganelli** [comment]
Just had one of the HATs students run into this yesterday evening, from trying to install coffea in conda. I didn't have them check the awkward version, but coffea 0.7.* pulled in uproot 5.*

**Comment by jpivarski** [comment]
If conda is installing an incompatible combination, then this is a bug in [conda-forge/coffea-feedstock](https://github.com/conda-forge/coffea-feedstock). If you're still seeing it, raise that issue there. For now, though, I'll be closing this issue here since it's not Uproot-related.
