### ISSUE TITLE
Issue converting boost_histogram to root histogram

### ISSUE THREAD

**Issue by mghern** [scikit-hep/uproot5#981]
Uproot 5 isn't correctly handling boost_histogram to root object conversion. Just for refence I've attached 4.3.7 which works as expected. (edit: updating to boost_histogram 1.4.0 fixed this, was previously on 1.3.1)
```python
>>>import uproot, boost_histogram as bh, numpy as np
>>>print(uproot.__version__)
>>>hist= bh.Histogram(bh.axis.Regular(20, 5, 30))
>>>hist.fill(np.arange(10))
>>>with uproot.recreate("hist.root") as root_file:
>>>root_file["hist"] = hist
5.0.12
AttributeError: 'Histogram' object has no attribute 'storage_type'
```
For reference this works as expected on 4.3.7
```python
>>>import uproot, boost_histogram as bh
>>>print(uproot.__version__)
>>>hist= bh.Histogram(bh.axis.Regular(20, 5, 30))
>>>hist.fill([1]*5)
>>>with uproot.recreate("hist.root") as root_file:
>>>root_file["hist"] = hist
4.3.7
```

**Comment by jpivarski** [comment]
> (edit: updating to boost_histogram 1.4.0 fixed this, was previously on 1.3.1)

I think that was it: the boost-histogram version. I just tried it (with boost-histogram 1.4.0) and didn't encounter any errors.

So this is resolved, right? I'll close it, and if you disagree, just follow up on this thread with what isn't working.
